### ISSUE TITLE
Provide IEV as a document layout type

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#1]
IEV documents (IEC 60050-x) uses a special bilingual layout provided here. So they are IEC Standards but use a different layout. 

http://www.iec.ch/standardsdev/resources/draftingpublications/writing_formatting/IEC_template/iev_standard_template.htm

**Comment by opoudjis** [comment]
... Why would we provide Metanorma encoding of IEV, when they are already publishing online as https://opendata.iec.ch/#/, in a far more appropriate format for IEV?

**Comment by ronaldtse** [comment]
Because IEV is the published content of IEC 60050, they still need to publish the paid standard (which consists of the same content published on the IEV website/OpenData). We'll see what their reply is.

**Comment by ronaldtse** [comment]
The first step would be implementing only the English layout.

Page 1
<img width="500" alt="Screen Shot 2020-04-06 at 8 01 45 PM" src="https://user-images.githubusercontent.com/11865/78556367-74712180-7841-11ea-95fa-e4e02aca3903.png">

Page 2
<img width="483" alt="Screen Shot 2020-04-06 at 8 02 05 PM" src="https://user-images.githubusercontent.com/11865/78556389-7dfa8980-7841-11ea-8433-7a35aa8eaed2.png">

Page 3
<img width="490" alt="Screen Shot 2020-04-06 at 8 02 14 PM" src="https://user-images.githubusercontent.com/11865/78556406-84890100-7841-11ea-830c-7ac6ce400a46.png">

Page 4

<img width="492" alt="Screen Shot 2020-04-06 at 8 02 36 PM" src="https://user-images.githubusercontent.com/11865/78556439-910d5980-7841-11ea-8ff5-2f36f2770d5d.png">

Page 5

<img width="483" alt="Screen Shot 2020-04-06 at 8 02 46 PM" src="https://user-images.githubusercontent.com/11865/78556452-97033a80-7841-11ea-9813-d085ce40a914.png">

Page 6
<img width="500" alt="Screen Shot 2020-04-06 at 8 02 55 PM" src="https://user-images.githubusercontent.com/11865/78556462-9bc7ee80-7841-11ea-8d67-adb9d65e4525.png">

Page 7
<img width="502" alt="Screen Shot 2020-04-06 at 8 03 06 PM" src="https://user-images.githubusercontent.com/11865/78556473-a2566600-7841-11ea-82e4-de676424db50.png">

Done!

**Comment by opoudjis** [comment]
Have implemented an IEV document template. There is clearly idiosyncratic rendering for IEV (IEV citations instead of term numbers for clause 3), and modelling is needed for aspects of terms not hitherto modelled (specific use attributes, symbols, French equivalents in bilingual documents, additional language equivalents).

**Comment by opoudjis** [comment]
Treating `domain:[]` as usage information, repeating it after each term if present.

**Comment by opoudjis** [comment]
Have done preliminary implementation. Any refinements are to be ticketed separately.
