### ISSUE TITLE
Unable to cite IEV terms within content

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#113]
From: https://github.com/glossarist/iev-document/issues/10

Original source:

```adoc
==== degradation

detrimental change in ability to meet requirements

SEE: degraded state ({{<<IEV:192-02-25>>,192-02-25}}).

NOTE: Degradation may occur with storage or use, brought about by internal processes or effects of the environment.

NOTE: Degradation beyond specified limits may constitute a degraded state or failure.

NOTE: In a system context, degradation may also be caused by failures within the system.
```

The syntax is correct.

Rendered:
<img width="1056" alt="Screenshot 2021-11-16 at 1 03 01 PM" src="https://user-images.githubusercontent.com/11865/141924042-8388bcee-c1ff-46d2-9ece-30304adb8c67.png">

**Comment by opoudjis** [comment]
Inserting the IEV into references explicitly, as is required, this now renders correctly. However, in line with all termbase citations currently, "Termbase" is prefixed to the termbase citation:

<img width="476" alt="Στιγμιότυπο 2021-11-17, 23 32 36" src="https://user-images.githubusercontent.com/1911039/142201433-0de554bf-7d21-4d71-8c3f-94ee82d24447.png">

Do you want "Termbase" removed in the case of IEV? Do you want it removed in general?

**Comment by opoudjis** [comment]
No, we need to recognise an IEV termbase link within the current document as such: if this is an IEV 192 document, all termbase references to IEV 192 are internal
