### ISSUE TITLE
When authoritative source is IEV, [SOURCE] renders broken

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#116]
From: https://github.com/glossarist/iev-document/issues/14

Source:

```adoc
==== system

set of interrelated items that collectively fulfil a requirement

NOTE: A system is considered to have a defined real or abstract boundary.

NOTE: External resources (from outside the system boundary) may be required for the system to operate.

NOTE: A system structure may be hierarchical, e.g. system, subsystem, component, etc.

NOTE: Conditions of use and maintenance should be expressed or implied within the requirement.

[.source]
<<IEV,clause "151-11-27">>, by extension to suit the dependability context
```

Rendered as:
<img width="735" alt="Screenshot 2021-11-16 at 1 12 59 PM" src="https://user-images.githubusercontent.com/11865/141924882-8bf3819d-1c5d-414e-88eb-d93bbf963319.png">

**Comment by opoudjis** [comment]
If an explicit citation of `IEV` is given in the references, this works fine:

`* [[[IEV, IEV]]]`

I do not agree at all with a notion that IEV should not be cited. After all, 

`//* [[[ievtermbank,IEV]]], _IEV: Electropedia_`

why wouldn't we cite the IEV internally as `ievtermbank`? Why would we hard code anchors?

**Comment by ronaldtse** [comment]
> //* [[[ievtermbank,IEV]]], _IEV: Electropedia_

This is from the documentation on metanorma.org.

> why wouldn't we cite the IEV internally as ievtermbank? Why would we hard code anchors?

See [metanorma.org.](https://www.metanorma.org/author/topics/document-format/section-terms/)

Moreover, the correct citation practice is to cite IEC 60050 instead of to "IEV" (see docs)

**Comment by ronaldtse** [comment]
I don't mind requiring an encoded reference but that **needs to be made clear on documentation** on **how to cite from the IEV**. Right now it is not doing that at all.

**Comment by opoudjis** [comment]
Works once:

a. IEV explicitly included in bibliography
b. scripts/split_codes.rb decoded (`get_source_string()` was not returning anything, and not coping with nbsp in IEC 60050 in source.

<img width="483" alt="Στιγμιότυπο 2021-11-17, 23 56 44" src="https://user-images.githubusercontent.com/1911039/142205023-350e0d9e-81bd-4d78-995c-ee3ce1434403.png">
