### ISSUE TITLE
Add document subtype IEV (IEC Electropedia, IEC 60050 series)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#122]
Just like how ISO has the vocabulary document type (https://github.com/metanorma/metanorma-iso/issues/473), the IEV document is also of a different type.

Most importantly, the terminology IDs are **NOT** under Clause 3:

See: https://github.com/metanorma/mn-samples-iec-iev
<img width="706" alt="Screenshot 2021-11-19 at 12 51 57 PM" src="https://user-images.githubusercontent.com/11865/142566930-c589b9bb-3b1f-4b5d-a240-e11d30b20698.png">

<img width="649" alt="Screenshot 2021-11-19 at 12 52 12 PM" src="https://user-images.githubusercontent.com/11865/142566944-7acfa339-8a27-4c35-905c-8937963350d4.png">

Critically we need to ensure compliance with the IEC Directives Supplement, Annex SK:
https://www.iec.ch/members_experts/refdocs/iec/isoiecdir1%7Bed15.0%7Den-IECsup.pdf

The numbering is as such because a term number is not considered a clause according to ISO/IEC Directives, it is a "term identifier".
<img width="1069" alt="Screenshot 2021-11-19 at 1 05 34 PM" src="https://user-images.githubusercontent.com/11865/142568081-ac56c89c-52f6-4b0b-98fb-73e1f1334c23.png">

**Comment by opoudjis** [comment]
> Just like how ISO has the vocabulary document type (metanorma/metanorma-iso#473), the IEV document is also of a different type.

I've already made IEV documents have subtype vocabulary.

**Comment by opoudjis** [comment]
As far as I can tell, I'm in conformance here.
