### ISSUE TITLE
Update docidentifier

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iec#154]
Source issue: https://github.com/metanorma/metanorma-iec/issues/153#issuecomment-1292277216

- [ ] no need to put `ED x` in the `docidentifier`.

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/198075814-fa9729c4-3b38-45f7-bcd0-e09109b20de3.png)

Resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/198214620-27b3f75e-70da-4a52-82fa-1053164eb130.png)

Metanorma presentation XML:
```xml
<docidentifier type="ISO">ISO/IEC/TR 30167 ED 1</docidentifier>
```

Example adoc:
```adoc
= Internet of things
:docnumber: 30167
:publisher: ISO;IEC
:copyright-holder: ISO;IEC
:tc-docnumber: 17301
:edition: 1
:revdate: 2021-06-01
:copyright-year: 2021
:language: en
:title-intro-en: Internet of things (IoT)
:title-main-en: Underwater communication technologies for IoT
:doctype: technical-report
:docstage: 60
:docsubstage: 92
...
```

- [x] add `docidentifier` with year into XML (rendering on page header)

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/198215991-ecde1edb-c3e5-40eb-af2b-297a247a179c.png)

document.adoc example:
```
= Smart manufacturing standards map
:docnumber: 63306
:partnumber: 1
:publisher: ISO;IEC
:copyright-holder: ISO;IEC
:tc-docnumber: 17301
:edition: 1
:revdate: 2020-12-01
:copyright-year: 2020
:language: en
:title-intro-en: Smart manufacturing standards map (SM2)
:title-part-en: Framework
:doctype: technical-report
:docstage: 60
:docsubstage: 92
...
```

**Comment by Intelligent2013** [comment]
- [ ] add `docidentifier` with year and month into XML (rendering on cover page, left side)

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/198297856-2243ea70-5894-48e5-8c6d-f5cec7e91642.png)

**Comment by Intelligent2013** [comment]
UPDATE: if document is multi-language, then lang codes delimit by `-`.
![image](https://user-images.githubusercontent.com/5559926/198300771-cf9931e1-9216-441b-a41a-63f019456995.png)

**Comment by opoudjis** [comment]
This is all relevant to pubid-iec. There is contradictory advice from IEC on identifiers, and I'm not going to change my code to deal with it: there needs to be a single source of truth about identifiers, and that is pubid-iec.

**Comment by opoudjis** [comment]
Issue put on hold, pending implementation of it in pubid-iec

**Comment by ronaldtse** [comment]
> This is all relevant to pubid-iec. There is contradictory advice from IEC on identifiers (I put ED in on IEC advice at the time), and I'm not going to change my code to deal with it: there needs to be a single source of truth about identifiers, and that is pubid-iec.

While two of these are bugs in pubid-iec, the problem in Metanorma is that:
1. There are multiple pubid manifestations of a document (with edition, with year no edition), these are used in various places in the rendering
2. PDF needs to select the proper pubid manifestation provided in the XML

If Metanorma XML does not provide the pubid manifestations, we cannot choose the correct identifiers in the PDF rendering process.

**Comment by opoudjis** [comment]
The variants still need to come from a single source of truth, and that source of truth is pubid-iec. If that gem exists, any modifications in metanorma-iec not using pubid-iec are a temporary kludge

**Comment by ronaldtse** [comment]
> The variants still need to come from a single source of truth, and that source of truth is pubid-iec. If that gem exists, any modifications in metanorma-iec not using pubid-iec are a temporary kludge

Yes, we need to have issues resolved in pubid-iec. I don't know if metanorma-iec/relaton-iec currently utilize pubid-iec.

**Comment by opoudjis** [comment]
metanorma-iec currently does not. I'm saying, I shouldn't invest the effort, if pubid-iec is coming (at a reasonable timeframe).

**Comment by opoudjis** [comment]
pubid-iec is still under active development...

**Comment by opoudjis** [comment]
Seems to have settled.

**Comment by opoudjis** [comment]
Have adopted pubid-iec

**Comment by opoudjis** [comment]
* no need to put ED x in the docidentifier.

If you specify

`:edition: 1`

You will get:

`<docidentifier type="ISO">ISO/IEC TR 30167:2021 ED1</docidentifier>`

If you do not specify an edition at all, you will get:

`<docidentifier type="ISO">ISO/IEC TR 30167:2021</docidentifier>`

Strongly suggest, @Intelligent2013, this is correct behaviour: I have removed the default setting of editions to 1.

If `ED1` is wrong, please raise an issue with pubid-iec

If you want two identifiers, one with the edition and one without, let me know.

**Comment by opoudjis** [comment]
>  * add docidentifier with year into XML (rendering on page header)

````
<docidentifier type="ISO">ISO/IEC TR 63306-1:2020</docidentifier>
<docidentifier type="iso-undated">ISO/IEC TR 63306-1</docidentifier>
````

**Comment by opoudjis** [comment]
> add docidentifier with year and month into XML (rendering on cover page, left side)

This is a brand new requirement. Following your sample header, I will only provide it if `revdate` is populated, as type iso-revdate.

`<docidentifier type="iso-revdate">ISO/IEC TR 63306-1:2020-12(en)</docidentifier>`

I am ignoring days, per your example; let me know if I should not.

**Comment by opoudjis** [comment]
Pending:

https://github.com/metanorma/pubid-iec/issues/114
https://github.com/metanorma/pubid-iec/issues/115

**Comment by Intelligent2013** [comment]
IEC XSLT updated for `<docidentifier type="iso-revdate">` and `docidentifier type="iso-undated"`.

**Comment by opoudjis** [comment]
Now pending https://github.com/metanorma/pubid-iec/issues/127

**Comment by opoudjis** [comment]
Now pending https://github.com/metanorma/pubid-cen/issues/19
