### ISSUE TITLE
Titles with abbreviations that cannot be case-changed

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#157]
In some IEC titles they contain particular abbreviations that cannot be case-changed, "IoT".

From @intelligent2013:

On the cover pdf, the title renders 'as is':
![image](https://user-images.githubusercontent.com/5559926/198328181-2559a60e-c43b-44ad-961c-3ea9deb1023a.png)

Before preface and main sections, the title renders in upper-cased, but except acronym `IoT`:
![image](https://user-images.githubusercontent.com/5559926/198328266-3ae5aecf-0708-443d-b3c9-2f81bc5fb966.png)

I see two options:
- add an additional document attribute (similar to BIPM's `:title-cover-en:` https://www.metanorma.org/author/bipm/ref/document-attributes/)
- add text formatting style like `Internet of things (%IoT%)`. `%text%` means 'reset any applied style' (`%` just for example, I don't sure at all that it allowed). In NISO STS XML there is the element `roman` for this purpose (https://github.com/metanorma/mnconvert/issues/222)

_Originally posted by @Intelligent2013 in https://github.com/metanorma/metanorma-iec/issues/153#issuecomment-1293699724_

**Comment by opoudjis** [comment]
Markup is the correct and more generalised approach. We need a flag that this span of text is not to have its case changed. Or else, if we could be confident that this only ever happens to abbreviations, we need markup that this is an abbreviation. But I don't know that we can be confident of that.

This is formatting markup. I'm not finding precedent for this as markup, but it would be the equivalent of CSS text-transform:none, overriding any capitalisation applied.

I'd like to mark this up as:

````
:title-cover-en: Internet of things [css text-transform:none]#IoT#.
````

which would end up in XML as:

````
<title>Internet of things <span style="text-transform:none">IoT</span></title>
````

And I am really opposed to reinventing CSS for styling text. Whatever we do, it is going to involve markup in XML.

**Comment by opoudjis** [comment]
So @Intelligent2013 I suggest the following:

1. You change the implementation of all-caps transformation in XSLT, so that it skips any `span` with `style=text-transform:...`
2. I process any instances of `span/[@style=text-transform=...]` in Presentation XML, so you don't need to deal with them—with the exception of `span/[@style=text-transform=none]`. So for example, I would translate `<span style="text-transform:uppercase">abc</span>` to `<span style="text-transform:none">ABC</span>`. You would normally ignore `span/[@style=text-transform=none]`, but, when you come to changing the case of any text in XSLT, you would skip any such spans.

I dare say that, even if we went for a more semantic approach, this is how it would end up implemented anyway.

**Comment by Intelligent2013** [comment]
@opoudjis I agree with your proposal.

I've tried to generate the presentation XML, but the titles in `<p class="zzSTDTitle1"...` don't contain the `span` tags:
```xml
<title language="en" format="text/plain" type="main">Internet of things (<span style="text-transform:none">IoT</span>) — Underwater communication technologies for <span style="text-transform:none">IoT</span></title>
...
<preface>
<p class="zzSTDTitle1" displayorder="3">INTERNATIONAL ELECTROTECHNICAL COMMISSION</p>
<p class="zzSTDTitle1" displayorder="4">____________</p><p class="zzSTDTitle1" displayorder="5"> </p>
<p class="zzSTDTitle1" displayorder="6"><strong>INTERNET OF THINGS (IOT) — UNDERWATER COMMUNICATION TECHNOLOGIES FOR IOT</strong></p>
...

<sections>
<p class="zzSTDTitle1" displayorder="10"><strong>Internet of things (IoT) — Underwater communication technologies for IoT</strong></p>

```



My `Gemfile`:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"
gem "metanorma-iec", git: "https://github.com/metanorma/metanorma-iec", branch: "main"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "main"
```

**Comment by opoudjis** [comment]
The middle titles are populated with the metadata values that are used to populate HTML/DOC cover pages and boilerplate; but titles in those values are not preserving their markup. (It's deliberate design that the inline markup of Metanorma is HTML-compatible; if that becomes an issue, we will deal with it.)

**Comment by opoudjis** [comment]
Memo: a more precise rendering of metadata titles into HTML is available at metanorma-itu, `Metadata::titleset()`:

````ruby
        @isodoc = IsoDoc::ITU::HtmlConvert.new({})
        value = isoxml.at(ns(xpath)) or return
        out = @isodoc.noko do |xml|
          xml.span do |s|
            value.children.each { |c| @isodoc.parse(c, s) }
          end
        end.join
        set(key, out.sub(%r{^<span>}, "").sub(%r{</span>$}, ""))
````

Can generalise that if needed, but I don't think it is.

**Comment by opoudjis** [comment]
Uhoh: capitalisation is capitalising tags:

````
<strong>INTERNET OF THINGS <SPAN STYLE="TEXT-TRANSFORM:NONE">IOT</SPAN> — UNDERWATER COMMUNICATION TECHNOLOGIES FOR IOT</strong>
````

**Comment by opoudjis** [comment]
@Intelligent2013 please find updated Presentation XML for IEC attached.

[a.presentation 2.xml.zip](https://github.com/metanorma/metanorma-iec/files/14317556/a.presentation.2.xml.zip)

**Comment by Intelligent2013** [comment]
@opoudjis the title in the `sections` generated correctly:
```xml
	<sections>
		<p class="zzSTDTitle1" displayorder="9">
			<strong>Internet of things <span style="text-transform:none">IoT</span> — Underwater communication technologies for IoT</strong>
		</p>
```

but in the `preface` it uppercased even in `<span style="text-transform:none">`:
```xml
	<preface>
...
		<p class="zzSTDTitle1" displayorder="6">
			<strong>INTERNET OF THINGS <span style="text-transform:none">IOT</span> — UNDERWATER COMMUNICATION TECHNOLOGIES FOR IOT</strong>
		</p>
```

**Comment by Intelligent2013** [comment]
I've updated XSLT for `<span style="text-transform:none">`:
![image](https://github.com/metanorma/metanorma-iec/assets/5559926/70037a49-0671-4d93-97fd-2eac43584e2d)
