### ISSUE TITLE
Terms and definition “domain” specifier not being rendered

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#16]
According to https://github.com/metanorma/mn-native-pdf/issues/44 the Word output is not rendering the domain identifier.

**Comment by opoudjis** [comment]
isodoc implementation is assuming that domain has been seen in XML before the definition paragraph.  That is not the case in the sample document; will resolve in postprocessing XML

**Comment by ronaldtse** [comment]
In case it wasn’t clear, this issue only occurred in IEC, not ISO.

**Comment by opoudjis** [comment]
Yes, but it was an artefact of where domain happened to occur in the document.

**Comment by ronaldtse** [comment]
Great, just wanted to be sure there weren’t any conflicts.
