### ISSUE TITLE
XML element should be `iec-standard`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#17]
Right now all IEC documents show as:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<iso-standard xmlns="http://riboseinc.com/isoxml">
<bibdata type="standard">
...
```

This is blocking https://github.com/metanorma/mn-native-pdf/pull/16 .

**Comment by opoudjis** [comment]
I don't think this is a bug at all, since ISO and IEC expressly use the same grammar. In fact, I think differentiating them is counterproductive.

Fixing anyway. Yelling at stupid syntax changes for the sake of it suppressed.

**Comment by opoudjis** [comment]
Added stupidity: it's the same goddamn grammar, but I have to manufacture a completely different grammar artefact now, because of a quite arbitrary looking XSLT navigation requirement.

This kind of busywork is not welcome.

**Comment by opoudjis** [comment]
New grammar created.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
