### ISSUE TITLE
PDF: Landscape mode is not working

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iec#193]
IEC/TR 80002-3:2014 (https://github.com/metanorma/mn-samples-bsi/pull/214) document includes a large table that should be shown in landscape mode, which is indicated by:
````
[%landscape]
<<<
````
However, it is shown in portrait mode regardless.

_Related to https://github.com/metanorma/mn-samples-bsi/issues/218._

**Comment by Intelligent2013** [comment]
There is a big task to support landscape mode for all SDOs (https://github.com/metanorma/mn-native-pdf/issues/449). Currently, it supported for ISO, IHO, BSI, BIPM and IEEE documents. I'll add the basic support for IEC (similar to ISO and IHO) shortly.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/221255455-3d8e2a08-334e-4d6e-b914-d3bf872b8670.png)
