### ISSUE TITLE
Registered trademark on the front cover

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iec#194]
Front page: Generated file has a registered trademark after IEC logo, unlike the original one.
Generated (left) vs. original (right):
![image](https://user-images.githubusercontent.com/55683568/220415437-6634538e-8d20-4b10-bc99-052885b383d5.png)
Registered trademark is also described in the footer of the generated file:
![image](https://user-images.githubusercontent.com/55683568/220415968-109a93f8-e8a2-47ca-b33c-716ebc76ff73.png)

The issue with two logos visible in the image above is already reported in https://github.com/metanorma/metanorma-iec/issues/190.

_Related to https://github.com/metanorma/mn-samples-bsi/issues/218._

**Comment by Intelligent2013** [comment]
IEC PDF XSLT developed based on the original IEC PDF sample from https://github.com/metanorma/mn-native-pdf/issues/120 - https://webstore.iec.ch/preview/info_iecfdis60721-3-0%7Bed2.0%7Den.pdf

It contains 'Registered trademark'
![image](https://user-images.githubusercontent.com/5559926/224508107-d5a8a372-d777-4866-82d1-e2bec29e1074.png)
and text in the footer:
![image](https://user-images.githubusercontent.com/5559926/224508126-d25b139f-41b4-4b40-87d4-05785220885a.png)

I need the exactly condition when we should show it and when hide it.

ping @ronaldtse

**Comment by Intelligent2013** [comment]
I've checked the IEC XSLT closely and currently:
-  registered trademark `®` after IEC logo
- `® Registered trademark of the International Electrotechnical Commission`
render in case of one copyright data (i.e. IEC only).

In case of "co-published" documents, these artifacts will be omitted. This was made in https://github.com/metanorma/metanorma-iec/issues/153 already.
