### ISSUE TITLE
PDF: Remove the dash before the title

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iec#195]
Front page: There is an extra dash before the title.
Generated (left) vs. original (right):
![image](https://user-images.githubusercontent.com/55683568/220416483-661ab35d-1033-494c-9181-46f57a635fc9.png)

_Related to https://github.com/metanorma/mn-samples-bsi/issues/218._

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/221255349-deefe96a-24e1-484b-81b1-c9bf47177676.png)
