### ISSUE TITLE
Add price code on the cover page

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iec#196]
Front page: Price code is missing.
Generated (left) vs. original (right):
![image](https://user-images.githubusercontent.com/55683568/220416852-c5412feb-b8ea-4cc0-a9ef-ad0389e1e66c.png)

_Related to https://github.com/metanorma/mn-samples-bsi/issues/218._

**Comment by opoudjis** [comment]
The price code was not nominated in the document attributes. Adding.

**Comment by opoudjis** [comment]
It is not showing up on the PDF cover indeed.

//bibdata/ext/price-code

````
ext><doctype language="">technical-report</doctype><doctype language="fr">Rapport technique</doctype><doctype language="en">Technical Report</doctype><editorialgroup identifier="IEC/SC A"><agency>IEC</agency><subcommittee number="A" type="SC">Common aspects of electrical equipment used in medical practice</subcommittee></editorialgroup><ics><code>11.040.01</code><text>Medical equipment in general</text></ics><structuredidentifier><project-number part="3">IEC 80002</project-number></structuredidentifier><stagename abbreviation="TR">Technical Report</stagename><price-code>U</price-code></ext></bibdata>
````

**Comment by opoudjis** [comment]
Ticket was implemented in https://github.com/metanorma/metanorma-iec/issues/42

**Comment by Intelligent2013** [comment]
Price code is showing on the PDF inner cover page (3rd page):
![image](https://user-images.githubusercontent.com/5559926/224474956-c371a6cd-f526-47a7-85a2-03b4f112ad46.png)

But with twice `PRICE CODE`. Will fix.

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/224475621-7505dcc2-9773-416a-878b-4dfaee3d3189.png)
