### ISSUE TITLE
Add source to figures (and tables)

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iec#198]
Similar to https://github.com/metanorma/metanorma-iso/issues/929.

Figures A.1 and A.2 are taken from outer source, which is noted differently in the original and generated file.
Generated (left) vs. original (right):
![image](https://user-images.githubusercontent.com/55683568/220421250-9c897ecf-db4c-4d27-a9ad-c2b140c45204.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/220559896-30123e4c-c7e3-4ec7-9de4-451c1a4cba5f.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/220559840-58a757fd-1f72-41be-b7be-2de54255b549.png)

_Related to https://github.com/metanorma/mn-samples-bsi/issues/218._

**Comment by opoudjis** [comment]
In https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor128 , SOURCE is cited as with the current rendering. That is the only instance of a sourced figure in ISO/IEC DIR 2, and the discussion of figures in https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor388 does not talk about sources at all.

Given there is no explicit discussion of figure sourcing, and the example give in Clause 10 agrees with the new rendering, I will decline to address this issue, as reflecting an obsolete sourcing convention.

**Comment by ronaldtse** [comment]
@opoudjis for Tables and Figures I have seen enough ISO examples that SOURCE applies, and in fact in JIS Z 8301 and BS 0 this is the an official model. We will need to implement them, as you can already see this in the JIS example document.

**Comment by opoudjis** [comment]
By default, `source` will render identically to term source.

**Comment by opoudjis** [comment]
For rendering of tables, will also move dl key to tfoot
