### ISSUE TITLE
Update document identifier in the header

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iec#200]
Document identifier in the header differs from the original one. Part number is fixed in https://github.com/metanorma/mn-samples-bsi/pull/237 and `doctype` (TR) is fixed in https://github.com/metanorma/mn-samples-bsi/pull/238. However, there are two remaining differences: edition is given in the generated file, while the year is missing.

Generated (left) vs. original (right):
![image](https://user-images.githubusercontent.com/55683568/220426633-6eb06077-18f4-4142-8cd9-4a150ac63931.png)

_Related to https://github.com/metanorma/mn-samples-bsi/issues/218._

**Comment by opoudjis** [comment]
Awaiting https://github.com/metanorma/metanorma-iec/issues/154

**Comment by opoudjis** [comment]
This is *almost* fixed with #154 

Only remaining issue is spacing in the docidentifier: it is ending up as IEC/TR80002-3 ED 1. Investigating...

**Comment by opoudjis** [comment]
New and unexpected problem: Publishers are to be passed to pubid as abbreviations, but the `:publisher:` value can be the complete name. This requires preprocessing to prevent it.

**Comment by opoudjis** [comment]
Getting year and edition now:

![Screenshot 2023-12-30 at 18 21 06](https://github.com/metanorma/metanorma-iec/assets/1911039/cc8d44dc-7c96-4c35-89b3-581907798935)

**Comment by opoudjis** [comment]
Edition was made obligatory in https://github.com/metanorma/metanorma-iec/issues/15. If the edition number is to be skipped, omit it from the document identifiers: we have not established consistent behaviour from IEC, and we have gone back and forth on this a couple of times now.
