### ISSUE TITLE
Add source to figures and tables

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iec#222]
Follow-on from https://github.com/metanorma/metanorma-iec/issues/198

There is a new `<source>` element added to figures and tables. Render it like you do `termsource`: I will have already inserted any tags and brackets around it in Presentation XML. In the case of it being part of a table, treat it like the notes following a table (both are supposed to be inserted in tfoot.)

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/229371570-53226009-fc0b-4cff-9e5b-c357b4b72d38.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 Can you please help confirm that the IEC Figure Source notes are supposed to render as displayed in the screenshot? I find it strange that there is not a "SOURCE: " prefix. Thanks!

**Comment by Intelligent2013** [comment]
@ronaldtse yes, there isn't "SOURCE: " prefix in the original PDF:
![image](https://user-images.githubusercontent.com/5559926/229425666-b52a64b6-a381-4b65-ac8e-88323329a6a3.png)

Source issue: https://github.com/metanorma/metanorma-iec/issues/198
Original PD IEC/TR 80002-3:2014 PDF: https://github.com/metanorma/mn-samples-bsi/issues/137

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !
