### ISSUE TITLE
IEC Preface title now in Presentation XML

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iec#236]
Results from https://github.com/metanorma/metanorma-jis/issues/13

I am refactoring the preface, so that it now contains explicit text to be rendered, in the order it is to be rendered.

In IEC, there is a document title at the start of the preface (before the foreword), repeated at the start of the main section (before the scope). As a result of the current refactoring, the document title at the start of the preface shall now be explicitly included in Presentation XML:

````
<preface><clause type="toc" id="_4b0077de-43b0-4178-99b2-1456df09089f" displayorder="1"><title depth="1">Contents</title></clause><pagebreak displayorder="2"/>
<p class="zzSTDTitle1" displayorder="3">INTERNATIONAL ELECTROTECHNICAL COMMISSION</p>
<p class="zzSTDTitle1" displayorder="4">____________</p>
<p class="zzSTDTitle1" displayorder="5"> </p>
<p class="zzSTDTitle1" displayorder="6"><strong>INTERNATIONAL ELECTROTECHNICAL VOCABULARY —</strong></p><p class="zzSTDTitle1" displayorder="7"> </p>
<p class="zzSTDTitle2" displayorder="8"><strong>Part 192: Dependability</strong></p>

<p class="zzSTDTitle1" displayorder="9"> </p>

<foreword id="_foreword" obligation="informative" displayorder="10">
<title>FOREWORD</title>
...
````

So the text between the (new) ToC clause and the foreword is now being supplied in Presentation XML, and you will not be supplying it. You will still supply the title at the start of the main section (displayorder 6 through 9) until I get around to refactoring that code too.

**Comment by opoudjis** [comment]
In addition, the code to merge the boilerplate/legal-statement into the start foreword (or to make it the foreword, if none is supplied), unless this is an amendment, is moved to Presentation XML, instead of being done independently by PDF and HTML/DOC.

So

no foreword => `<preface><foreword>#{boilerplate/legal-statement/(children)}</foreword></preface>` 

existing foreword => `<preface><foreword>#{boilerplate/legal-statement/(children)}#{existing foreword}</foreword></preface>`

**Comment by Intelligent2013** [comment]
IEC XSLT updated:
![image](https://user-images.githubusercontent.com/5559926/234074613-a9125ca2-d265-4a11-b320-2b6a9b36535a.png)
