### ISSUE TITLE
TOC headings seems to break section names?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#32]
<img width="281" alt="image" src="https://user-images.githubusercontent.com/11865/78798299-6959f500-79eb-11ea-89a0-e6fb289b590b.png">

=> "INTRODUCTIONPrinciples and rules followed"

This is from https://github.com/glossarist/iev-document .

**Comment by ronaldtse** [comment]
@w00lf could you help take care of this? Thanks!

**Comment by opoudjis** [comment]
if you get to it before me, @w00lf, the simplification of TOC headings is in isodoc, header_strip().

**Comment by opoudjis** [comment]
... no, it is in the JS scripts.html; the code to build it statically is overridden.

**Comment by opoudjis** [comment]
This is from the comedy of errors of https://github.com/metanorma/isodoc/issues/79. The request to move away from Javascript dates from TWO YEARS AGO, and the followup to feature-improve static TOC has been unactioned as https://github.com/metanorma/isodoc/issues/113.

I will need to investigate what disabling static ToC will do.

**Comment by opoudjis** [comment]
So

* The cleanup of headings in Static ToC (Ruby) is much better than that in Dynamic ToC (JS), which is basically unimplemented.
* I have no idea if we are meant to be moving away from Dynamic ToC or not, metanorma/isodoc#79 is muddled and full of short term thinking.
* I have no idea if we are meant to use jQuery or not.
* I do know that replicating code to do the same thing in JS and Ruby is leading to confusion.
 * I am going to shove in a cheap jQuery function to implement the highlighting requested in metanorma/isodoc#113, and disable Dynamic ToC.

**Comment by ronaldtse** [comment]
We are meant to have a degradable Dynamic ToC. Ie. Even if there is no JS enabled the ToC still works, perhaps without highlighting.

**Comment by opoudjis** [comment]
There is no reason to implement the same functionality twice in this case. Urgent I speak to you.
