### ISSUE TITLE
Create IEC HTML style to reflect styling

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#33]
<img width="1137" alt="Screen Shot 2020-04-11 at 1 39 08 AM" src="https://user-images.githubusercontent.com/11865/79010784-3d7a7300-7b95-11ea-973b-41d01ebff3ac.png">

IEC uses Arial. General design should follow this:
https://www.iec.ch/members_experts/refdocs/iec/isoiecdir1-consolidatediecsup%7bed15.0.RLV%7den.pdf

@pierrefortier do you have time to create an HTML style for IEC? Thanks!

**Comment by opoudjis** [comment]
Be aware that there has been MASSIVE refactoring of the CSS since you last worked with us, Pierre, and any changes that go against that refactoring are going to make my life (or @w00lf 's) very uncomfortable.

Kindly use the attached as your starting point.

 https://metanorma.github.io/mn-samples-iec/documents/iec-rice.html

**Comment by ronaldtse** [comment]
@w00lf I'm going to assign this to you instead; the following two changes will suffice for us now:

1. Replace all instances of "Cambria" with "Arial". Beware we don't want to replace "Cambria Math"
2. Replace all instances of "#f7f7f7" with "#f5faff"

The changes I made so far are in the branch "feature/iec-style" #52 .

**Comment by opoudjis** [comment]
Be aware that the HTML font variables are set in lib/isodoc/iec/html_convert.rb, and is already using Arial for $bodyfont and $headerfont:

````
 def default_fonts(options)
        {
          bodyfont: (options[:script] == "Hans" ? '"SimSun",serif' : '"Arial",sans-serif'),
        headerfont: (options[:script] == "Hans" ? '"SimHei",sans-serif' : '"Arial",sans-serif'),
        monospacefont: ('"Courier New",monospace'),
        }
      end
````

**Comment by ronaldtse** [comment]
Done in https://github.com/metanorma/metanorma-iec/pull/52 .
