### ISSUE TITLE
Clause 3 "IEC Electropedia" phrase missing space between "at" and link

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#339]
From https://github.com/metanorma/iec-iso-jseg-15/issues/5

The Clause 3 "IEC Electropedia" phrase missing space between "at" and link.

<img width="581" alt="image" src="https://github.com/user-attachments/assets/2253f41f-d97a-412b-a2c6-d90e6e5b8871">

**Comment by opoudjis** [comment]
Artefact of elimination of end of line space insertion, because of the decision to not force CR in CJK text.

@ronaldtse this is what 6 years of vexatious edge cases from you gets.

**Comment by ronaldtse** [comment]
This text should be in an AsciiDoc template.

**Comment by opoudjis** [comment]
I'll do normative reference boilerplate as well, it has footnote in ITU.
