### ISSUE TITLE
Discrepancy with IEV layout and TOC content

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#34]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/11865/79018626-db2a6e00-7ba6-11ea-9826-2e6e9edf96b3.png">

https://webstore.iec.ch/preview/info_iec60050-171%7Bed1.0%7Db.pdf

**Comment by opoudjis** [comment]
This has just been resolved: https://github.com/glossarist/iev-document/issues/22
