### ISSUE TITLE
Tailor to IEC stage codes and their description

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#35]
Code | Desc
-- | -- 
PWI | Preliminary Work Item
NP | New Work Item Proposal
WD | Working Draft
CD | Committee Draft
CDV | Committee Draft for Vote
FDIS | Final Draft International Standard
IS | International Standard

**Comment by opoudjis** [comment]
Already done in https://github.com/metanorma/metanorma-iso/issues/342

**Comment by opoudjis** [comment]
A distinction is made in the XML between `stage/@abbreviation`, which is the foregoing, and `substage/@abbreviation`, which is the full throttle abbreviation including all the substages. The former is used in creating the identifier.
