### ISSUE TITLE
Introduce document attribute for 'colour inside' indication

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iec#40]
To generate the IEC cover pages in PDF (https://github.com/metanorma/mn-native-pdf/issues/109) we need to have the indication in the XML that document contains colour images, figures, etc.

![image](https://user-images.githubusercontent.com/5559926/80193742-09d22b00-8622-11ea-8711-b48123f33b9e.png)

from @ronaldtse:
> I think there should be an attribute in the document that expresses this. e.g. document attribute like :accessibility-color-inside: true.

**Comment by opoudjis** [comment]
Element added as `//bibdata/ext/accessibility-color-inside`
