### ISSUE TITLE
Introduce 'price code' property

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iec#42]
To generate the IEC cover pages in PDF (https://github.com/metanorma/mn-native-pdf/issues/109) we need to have 'price code' property in the XML.

![image](https://user-images.githubusercontent.com/5559926/80196903-a1397d00-8626-11ea-8b3e-c5acda5ab444.png)

This issue is to add this attributes.

**Comment by ronaldtse** [comment]
The structure of the IEC price code is described here:
https://www.iec.ch/members_experts/tools/pdf/IEC_DATA_FEEDS.pdf

<img width="1084" alt="Screen Shot 2020-11-27 at 8 33 11 PM" src="https://user-images.githubusercontent.com/11865/100449974-c546ca80-30ef-11eb-94ab-3ebfa7b747bb.png">

So in the metadata we probably only need to know the "price code group", which is just a string.

**Comment by opoudjis** [comment]
Adding as `:price-code:`, located in `//bibdata/ext/price-code`

**Comment by opoudjis** [comment]
Sample document:

[a.presentation.xml 2.zip](https://github.com/metanorma/metanorma-iec/files/5652510/a.presentation.xml.2.zip)
