### ISSUE TITLE
Introduce 'About ...' and URLs information

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iec#44]
To generate the IEC cover pages in PDF (https://github.com/metanorma/mn-native-pdf/issues/109) we need to have 'About...' and URLs  data in the XML. Sample document https://www.itu.int/en/ITU-D/Technology/Documents/Events2016/CI_Training_ARB_Tunis_April16/Session8/IEC_61000-4-5_2014.pdf:

![image](https://user-images.githubusercontent.com/5559926/80199735-56b9ff80-862a-11ea-8fe5-1513de0fe701.png)

This issue is to add these data.

**Comment by opoudjis** [comment]
This data belongs to boilerplate.

**Comment by opoudjis** [comment]
[a.presentation.xml.zip](https://github.com/metanorma/metanorma-iec/files/5540766/a.presentation.xml.zip)
