### ISSUE TITLE
Introduce 'category of standard' property

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iec#45]
To generate the IEC cover pages in PDF (https://github.com/metanorma/mn-native-pdf/issues/109, https://github.com/metanorma/mn-native-pdf/issues/121) we need to have 'category of standard' property in the XML:

>from @ronaldtse :
> these "Functions" are allowed:
> - Basic EMC Publication
> - Basic Safety Publication
> - Basic Environment Publication
> - Basic Quality Assurance Publication

PDF cover page example:

![image](https://user-images.githubusercontent.com/5559926/80201186-6cc8bf80-862c-11ea-8c9c-dd1395860b28.png)

This issue is to add this property.

**Comment by opoudjis** [comment]
Add Horizontal Standard as a category.

**Comment by opoudjis** [comment]
To be realised as:

`:docsubtype: { emc | safety | environment | quality-assurance | horizontal }`

**Comment by opoudjis** [comment]
Setting IEC to include both French and English doctype and docsubtype localisations in bibdata

**Comment by opoudjis** [comment]
There is no evidence whatsoever of the existence of the document subtypes:

* Basic Environment Publication
* Basic Quality Assurance Publication

The only attestation of these online is https://github.com/metanorma/mn-native-pdf/issues/109#issuecomment-616762842. @ronaldtse, I'd rather have an IEC publication as a source of truth than a Github ticket written by one of us.

https://www.iec.ch/dyn/www/f?p=103:41:0::::FSP_ORG_ID,FSP_LANG_ID:10033,25 indicates there is a Basic EE [Energy Efficiency] Publication type, although I have no evidence this has ever been used, or rendered into French. 

I've made up French equivalents of those types, but they are bogus, and the bogosity is not mine...

**Comment by ronaldtse** [comment]
Sorry for the late reply:
> Add Horizontal Standard as a category.

Horizontal Standard is a true/false -- it's not a category. Any standard can be marked as a Horizontal Standard, and ISO is also introducing this.

**Comment by opoudjis** [comment]
Also, it is claimed >:-| , the "category of standard" is not a subtype of international-standard.

The solution becomes:

````
:docategory: { emc | safety | environment | quality-assurance }
:horizontal: { true | false }
````

**Comment by ronaldtse** [comment]
> claimed >:-|

Claimed courtesy of IEC:

<img width="501" alt="Screen Shot 2020-11-27 at 8 36 30 PM" src="https://user-images.githubusercontent.com/11865/100450219-3be3c800-30f0-11eb-9170-6e97a20e1970.png">

@opoudjis can we also add the `horizontal` attribute to ISO? ISO is also marking them soon.

**Comment by ronaldtse** [comment]
Do you want to rename `doccategory` to `functions-concerned` in alignment with IEC wording? I also believe these are multi-valued.

**Comment by opoudjis** [comment]
````
:function: { emc | safety | environment | quality-assurance }
:horizontal: { true | false }
````

**Comment by opoudjis** [comment]
@Intelligent2013 The realisations in Presentation XML are:

For horizontal = true

````
       <bibdata>
       <docnumber>1</docnumber>
       <language current="true">en</language>
       <ext>
  <doctype language=''>international-standard</doctype>
  <doctype language='fr'>Norme international</doctype>
  <doctype language='en'>International Standard</doctype>
<horizontal language=''>true</horizontal>
<horizontal language='fr'>Norme horizontale</horizontal>
<horizontal language='en'>Horizontal Standard</horizontal>
<function language=''>emc</function>
<function language='fr'>Publication fondamentale en CEM</function>
<function language='en'>Basic EMC Publication</function>
</ext>
       </bibdata>
````

For horizontal = false

````
<bibdata>
  <language current='true'>fr</language>
  <ext>
    <doctype language=''>international-standard</doctype>
    <doctype language='fr'>Norme international</doctype>
    <doctype language='en'>International Standard</doctype>
    <horizontal language=''>false</horizontal>
    <function language=''>emc</function>
    <function language='fr'>Publication fondamentale en CEM</function>
    <function language='en'>Basic EMC Publication</function>
  </ext>
</bibdata>
````

**Comment by Intelligent2013** [comment]
@opoudjis thank you.
