### ISSUE TITLE
Introduce 'Horizontal Standard' indication

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iec#46]
To generate the IEC cover pages in PDF (https://github.com/metanorma/mn-native-pdf/issues/109, https://github.com/metanorma/mn-native-pdf/issues/121) we need to know in the XML  that if standard is 'Horizontal Standard' - true/false.

From @ronaldtse (https://github.com/metanorma/mn-native-pdf/issues/109#issuecomment-612188151):
> Some other standards have a "HORIZONTAL STANDARD" label. We will need to handle this.

This issue is to add this attribute.

**Comment by opoudjis** [comment]
Horizontal Standard looks like an instance of Category of Standard from the sample docs. Merging into #45

**Comment by ronaldtse** [comment]
@opoudjis as per https://github.com/metanorma/metanorma-iec/issues/45#issuecomment-734809054:

Horizontal Standard is a true/false -- it's not a category. Any standard can be marked as a Horizontal Standard, and ISO is also introducing this.
