### ISSUE TITLE
Introduce 'CEN processing' indication

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iec#47]
To generate the IEC cover pages in PDF (https://github.com/metanorma/mn-native-pdf/issues/121#issue-598202931) we need to have CEN processing (true/false) attribute in the XML.

This issue is to add this attribute.

**Comment by ronaldtse** [comment]
Yes, this is a true/false value. Thanks.

**Comment by opoudjis** [comment]
`//bibdata/ext/cen-processing`
