### ISSUE TITLE
IEC stage codes should follow official list

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#5]
https://www.iec.ch/standardsdev/resources/processes/stage_codes.htm

```
Code | Meaning | Deliverable
-- | -- | --
ACD | Approved for CD | IS, TS, TR
ACDV | Approved for CDV | IS, TS, TR
ADTR | Approved for DTR | TR
ADTS | Approved for DTS | TS
AFDIS | Approved for FDIS | IS
APUB | Approved for publication | IS, TS, TR, PAS, ISH
BPUB | Being published | IS, TS, TR, PAS, ISH
CAN | Draft cancelled | IS, TS, TR, PAS, ISH
CD | Draft circulated as CD | IS, TS, TR
CDM | CD to be discussed at meeting | IS, TS, TR
CCDV | Draft circulated as CDV | IS
CDISH | Draft circulated as DISH | ISH
CDVM | Rejected CDV to be discussed at a meeting | IS
CFDIS | Draft circulated as FDIS | IS
CDPAS | Draft circulated as DPAS | PAS
CDTR | Draft circulated as DTR | TR
CDTS | Draft circulated as DTS | TS
DTRM | Rejected DTR to be discussed at meeting | TR
DTSM | Rejected DTS to be discussed at meeting | TS
DECDISH | DISH at editing check | ISH
DECFDIS | FDIS at editing check | IS
DECPUB | Publication at editing check | IS, TS, TR, PAS
DEL | Deleted/abandoned | IS, TS, TR
DELPUB | Deleted publication | IS, TS, TR, PAS, ISH
NCDV | CDV rejected | IS
NDTR | DTR rejected | TR
NDTS | DTS rejected | TS
NFDIS | FDIS rejected | IS
PCC | Preparation of CC | IS, TS, TR
PNW | New work item proposal | IS, TS
PPUB | Publication issued | IS, TS, TR, PAS, ISH
PRVC | Preparation of RVC | IS
PRVDISH | Preparation of RVDISH | ISH
PRVD | Preparation of RVD | IS
PRVDPAS | Preparation of RVDPAS | PAS
PRVDTR | Preparation of RVDTR | TR
PRVDTS | Preparation of RVDTS | TS
PRVN | Preparation of RVN | IS, TS
PWI | Preliminary work item | IS, TS, TR
RDISH | DISH received and registered | ISH
RFDIS | FDIS received and registered | IS
RPUB | Publication received and registered | IS, TS, TR, PAS
TCDV | Translation of CDV | IS
TDISH | Translation of DISH | ISH
TDTR | Translation of DTR | TR
TDTS | Translation of DTS | TS
TFDIS | Translation of FDIS | IS
TPUB | Translation of publication | IS, TS, TR
WPUB | Publication withdrawn | IS, TS, TR, PAS, ISH
```

**Comment by opoudjis** [comment]
We are driving this from the internatinal harmonised codes at https://www.iso.org/stage-codes.html. Currently we have only mapped stage. Most of these involve stage and substage.

The translations require modelling of this being a translation of another standard. That can be modelled in `bibdata/relation[@type = 'translationOf']/bibitem/docidentifier`, which will be introduced by adding a `:translates:` document attribute for IEC.

**Comment by ronaldtse** [comment]
@opoudjis are you suggesting to create a translation mechanism for document stages between document flavors?

**Comment by opoudjis** [comment]
Mapping to ISO harmonised codes is in Annex SH of https://www.iec.ch/members_experts/refdocs/iec/isoiecdir-1-iecsup%7Bed12.0%7Den.pdf

**Comment by opoudjis** [comment]
Which means translation is already provided by IEC; we will use those numbers as we do in ISO gem for data entry, and map to the stage code in isodoc for rendering.

**Comment by opoudjis** [comment]
Stage Code | Code | Defn | Doctypes | Note |
| ---- | ---- | ---- | ---- | ---- |
3520 | 2CD .. 9CD | Circulation for comment | | NOT IN IEC WEBSITE
2099 | ACD | Approved for CD | IS, TS, TR | | NOT IN ANNEX SH, inferred
3099 | A2CD | Register for next applicable phase | | NOT IN IEC WEBSITE
3592 | A3CD ... A9CD | Return to drafting phase | | NOT IN IEC WEBSITE
3599 | ACDV | Approved for CDV | IS, TS, TR
4099 | ADIS | Register for next applicable phase | | NOT IN IEC WEBSITE
4095 | ADISSB | Preparation of text subcontracted to CO | | NOT IN IEC WEBSITE
ADTR | Approved for DTR | TR
ADTS | Approved for DTS | TS
AFDIS | Approved for FDIS | IS
9220 | AMW | Document under revision | | NOT IN IEC WEBSITE
2000 | ANW | Registration of new project |   | NOT IN IEC WEBSITE
5099 | APUB | Approved for publication | IS, TS, TR, PAS, ISH
5095 | APUBSB | Preparation of text subcontracted to CO | | NOT IN IEC WEBSITE
6000| BPUB | Being published | IS, TS, TR, PAS, ISH
2098 | CAN | Draft cancelled | IS, TS, TR, PAS, ISH
3020 | CD | Draft circulated as CD | IS, TS, TR
3092 | BWG | Return to drafting phase or redefine project | | NOT IN IEC WEBSITE
3591 | CDM | CD to be discussed at meeting | IS, TS, TR
4020 | CCDV | Draft circulated as CDV | IS
5020 | CDIS | Circulation for formal approval | | EXCLUDES PAS?
CDISH | Draft circulated as DISH | ISH
4091 | CDVM | Rejected CDV to be discussed at a meeting | IS
CFDIS | Draft circulated as FDIS | IS
5020 | CDPAS | Draft circulated as DPAS | PAS | SPECIFIC TO PAS
CDTR | Draft circulated as DTR | TR
CDTS | Draft circulated as DTS | TS
4099 | DEC | Register for next applicable phase | | NOT IN IEC WEBSITE, NOT DISTINCT FROM ADIS
DTRM | Rejected DTR to be discussed at meeting | TR
DTSM | Rejected DTS to be discussed at meeting | TS
DECDISH | DISH at editing check | ISH
DECFDIS | FDIS at editing check | IS
DECPUB | Publication at editing check | IS, TS, TR, PAS
2098 | DEL | Deleted/abandoned | IS, TS, TR | NOT DISTINCT FROM CAN 
9960 | DELPUB | Deleted publication | IS, TS, TR, PAS, ISH
3098 | DREJ | Abandon | | NOT IN ANNEX SH
3097 | MERGED | Merge or split project | | NOT IN IEC WEBSITE
4093 | Repeat enquiry | | NOT IN IEC WEBSITE
5092 | NCD | Return to drafting phase | | NOT IN IEC WEBSITE
NCDV | CDV rejected | IS
NDTR | DTR rejected | TR
NDTS | DTS rejected | TS
NFDIS | FDIS rejected | IS
PCC | Preparation of CC | IS, TS, TR
1000 | PNW | New work item proposal | IS, TS
6060 | PPUB | Publication issued | IS, TS, TR, PAS, ISH
PRVC | Preparation of RVC | IS
PRVDISH | Preparation of RVDISH | ISH
PRVD | Preparation of RVD | IS
PRVDPAS | Preparation of RVDPAS | PAS
PRVDTR | Preparation of RVDTR | TR
PRVDTS | Preparation of RVDTS | TS
PRVN | Preparation of RVN | IS, TS
0000 | PWI | Preliminary work item | IS, TS, TR
5000 | RDIS | Registration for formal approval | | NOT IN IEC WEBSITE
RDISH | DISH received and registered | ISH
RFDIS | FDIS received and registered | IS
RPUB | Publication received and registered | IS, TS, TR, PAS
9092 | RR | Review report | | NOT IN IEC WEBSITE
TCDV | Translation of CDV | IS
TDISH | Translation of DISH | ISH
TDTR | Translation of DTR | TR
TDTS | Translation of DTS | TS
TFDIS | Translation of FDIS | IS
TPUB | Translation of publication | IS, TS, TR
9599| WPUB | Publication withdrawn | IS, TS, TR, PAS, ISH

**Comment by opoudjis** [comment]
The final foregoing table is what I'm going to implement.

**Comment by ronaldtse** [comment]
This link is Edition 15 for 2019: https://www.iec.ch/members_experts/refdocs/iec/isoiecdir1-consolidatediecsup%7Bed15.0.RLV%7Den.pdf
