### ISSUE TITLE
Numbered lines in DOC output

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iec#53]
Regarding the IEC sample document: https://github.com/metanorma/mn-samples-iec/blob/master/sources/iec-rice.adoc

Every time the DOC file is generated the line numbering option in Word gets activated.
(The "Track Changes" option gets activated as well.)

![cap-doc](https://user-images.githubusercontent.com/33627611/81186567-f2c7fd00-8f80-11ea-8ca5-e7cec91f8ef0.PNG)

**Comment by ronaldtse** [comment]
I think this is an option?

**Comment by manuel489** [comment]
> I think this is an option?

@ronaldtse , yes it is an option,  hence, it is removable. However, this option is activated every time the file is generated, and considering that this issue is not present in other flavors. I thought prudent to tag it as a bug.

**Comment by opoudjis** [comment]
All drafts have line numbering. That is a requirement from IEC and NIST for their drafts (so that reviewers can cite by line number). So it's not a bug.

**Comment by ronaldtse** [comment]
> That is a requirement from IEC and NIST for their drafts (so that reviewers can cite by line number).

I wanted to say otherwise but after checking the drafts I think this might be true. As long as there is a way to turn this off, it's good.
