### ISSUE TITLE
Additional text added to a footnote paragraph in XML

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iec#54]
*From document: https://github.com/metanorma/mn-samples-iec/blob/master/sources/iec-rice.adoc*

Coming from a reference footnote paragraph, there is an additional text (`ISO DATE: `) added automatically to the XML source.

*Source hunk:*
````
* [[[ISO16634,ISO 16634:--]]] footnote:[Under preparation. (Stage at the time of publication ISO/DIS 
16634)], _Cereals, pulses, milled cereal products, oilseeds and animal feeding stuffs -- Determination 
of the total nitrogen content by combustion according to the Dumas principle and calculation of 
the crude protein content_
````
*XML:*
````
<note format="text/plain">ISO DATE: Under preparation. (Stage at the time of publication ISO/DIS 16634)</note>
````

*PDF:*
![image](https://user-images.githubusercontent.com/55683568/72927026-be279100-3d55-11ea-8af8-7d655aedc047.png)

*DOC:*
![image](https://user-images.githubusercontent.com/55683568/72927040-c384db80-3d55-11ea-916e-6a772e28ab51.png)

**Comment by opoudjis** [comment]
Already resolved in https://github.com/metanorma/metanorma-iso/issues/397
