### ISSUE TITLE
Remaining issues in PDF version vs DOC

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iec#55]
*This issue is related to https://github.com/metanorma/mn-native-pdf/issues/58*

- The page numbering in front page area is done with Arabic numbers in PDF, and Roman numbers in DOC. (The ordering differs as well.)

*PDF:*
![diff-alex-pdf](https://user-images.githubusercontent.com/33627611/81211651-ad67f780-8fa1-11ea-8fa8-1b4fa3c9ddde.PNG)

*DOC:*
![diff-alex-doc](https://user-images.githubusercontent.com/33627611/81211674-b6f15f80-8fa1-11ea-9c99-c755e0e57846.PNG)

- Missing "INTERNATIONAL ELECTROTECHNICAL COMMISSION" at the beginning of the main content

*PDF:*
![diff2-alex-pdf](https://user-images.githubusercontent.com/33627611/81211110-e81d6000-8fa0-11ea-85ba-99f0066b2075.PNG)

*DOC:*
![diff2-alex-doc](https://user-images.githubusercontent.com/33627611/81211851-fd46be80-8fa1-11ea-9eb3-f92cfde893fe.PNG)

- Missing clause reference in quotation block

*PDF:*
![diff3-alex-pdf](https://user-images.githubusercontent.com/33627611/81211972-2b2c0300-8fa2-11ea-849b-6ab94e07f589.PNG)

*DOC:*
![diff3-alex-doc](https://user-images.githubusercontent.com/33627611/81211980-2ebf8a00-8fa2-11ea-9539-ee0a979ca6cb.PNG)

- Vertical spacing between annex title and paragraph is larger in PDF

*PDF:*
![diff4-alex-pdf](https://user-images.githubusercontent.com/33627611/81212288-aab9d200-8fa2-11ea-8bea-0e784f28c68c.PNG)

*DOC:*
![diff4-alex-doc](https://user-images.githubusercontent.com/33627611/81212292-ac839580-8fa2-11ea-98ba-75bb2fe53343.PNG)

- Missing clause reference in bibliography reference

*PDF:*
![diff5-alex-pdf](https://user-images.githubusercontent.com/33627611/81212466-ed7baa00-8fa2-11ea-9d86-9800045e048c.PNG)

*DOC:*
![diff5-alex-doc](https://user-images.githubusercontent.com/33627611/81212536-04ba9780-8fa3-11ea-962f-2ddaeb3534c3.PNG)

- In PDF version, there is jump in the section numbering from `3` to `6` (instead of `4`)

*PDF:*
![diff6-alex-pdf](https://user-images.githubusercontent.com/33627611/81213140-f5881980-8fa3-11ea-9a02-2545be4a3e6e.PNG)

*DOC:*
![diff6-alex-doc](https://user-images.githubusercontent.com/33627611/81213151-fa4ccd80-8fa3-11ea-9215-e4dc8e899db3.PNG)

Thanks!

**Comment by Intelligent2013** [comment]
> The page numbering in front page area is done with Arabic numbers in PDF, and Roman numbers in DOC. (The ordering differs as well.)

Regarding https://github.com/metanorma/mn-native-pdf/issues/110 on front page should be Arabic numbers.

> Missing "INTERNATIONAL ELECTROTECHNICAL COMMISSION" at the beginning of the main content

Issue was fixed in https://github.com/metanorma/mn-native-pdf/issues/111

> Missing clause reference in quotation block

Issue was fixed earlier already.

> Vertical spacing between annex title and paragraph is larger in PDF

Vertical spacing will be aligned for https://github.com/metanorma/mn-native-pdf/issues/116

> Missing clause reference in bibliography reference

Issue was fixed earlier already.

> In PDF version, there is jump in the section numbering from 3 to 6 (instead of 4)

Fixed.


Updated PDF here: https://github.com/metanorma/mn-native-pdf/raw/gh-pages/documents/iec-rice.pdf

**Comment by manuel489** [comment]
Thanks @Intelligent2013 , 
There are other discrepancies against DOC version. But I think those are due to a disagreement in formatting. I will post them in a separated ticket. Do you know where I can find the original version of this document?

**Comment by Intelligent2013** [comment]
@manuel489 I don't know about the original version. Initially, I've developed XSLT for DOC version. Then I've changed styles to align these PDFs: https://github.com/metanorma/mn-native-pdf/issues/109.

**Comment by manuel489** [comment]
Ok @Intelligent2013 , thanks for the information. I'll checkout those PDFs and open another ticket that involves you and @opoudjis to talk about the remaining formatting discrepancies. Closing.
