### ISSUE TITLE
Duplicated appendix title in DOC

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iec#56]
*From sample document: https://github.com/metanorma/mn-samples-iec/blob/master/sources/iec-rice.adoc*

The "Appendix 1" title is duplicated. 
(Also, notice that there is an additional line-break in the source block.)

*Markup hunk:*

````
[%appendix]
=== Appendix 1

[[samplecode]]
.Sample Code
====

[source,ruby]
--
puts "Hello, world."
%w{a b c}.each do |x| <1>
  puts x
end
--
<1> This is an annotation
====
````

*DOC:*
![nick-issue1-doc](https://user-images.githubusercontent.com/33627611/81216337-c031fa80-8fa8-11ea-9af7-ad9f9d379eff.PNG)

*PDF:*
![nick-issue1-pdf](https://user-images.githubusercontent.com/33627611/81216346-c45e1800-8fa8-11ea-9166-8747c1217d66.PNG)

**Comment by opoudjis** [comment]
> The "Appendix 1" title is duplicated.

That is absolutely the correct behaviour. If the title were instead "A study in scarlet", 

````
[%appendix]
=== A study in scarlet
````

would render as 

____
Appendix 1: A study in scarlet
____

In this case, it is the PDF that has incorrect behaviour: @Intelligent2013. Appendixes in ISO need to be explicitly labelled.

**Comment by opoudjis** [comment]
> (Also, notice that there is an additional line-break in the source block.)

Again, that is correct behaviour: there is meant to be a blank line between the sourcecode and the annotation callouts, to make it clear that the annotation callouts are separate from the source code. Again, @Intelligent2013, the PDF behaviour should be different.
