### ISSUE TITLE
Remove front page from Word layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#6]
IEC working documents do not have a "front page", they are added by the IEC editors.

This issue is to remove the front page, MN-IEC Word document should start with the ToC.

NOTE: This was reported by an IEC person.

**Comment by opoudjis** [comment]
...

That is not welcome news.

**Comment by opoudjis** [comment]
IEC working documents: does that mean that we can leave the "front page" alone if it is a published status document? Given that we have never been provided the cover page in Word, I guess the answer is no.

**Comment by ronaldtse** [comment]
@opoudjis if the document is published, it should be fine to add the front page — except we have not been given the front page in Word.

**Comment by opoudjis** [comment]
If we ever get it, I will update the gem. Right now, it is universally suppressed.

**Comment by ronaldtse** [comment]
In fact, it would be even better to use a document attribute to un-suppress the cover page. This way we will get requests to “update the cover page layout” instead of “implementing the cover page”.

**Comment by ronaldtse** [comment]
It’s just an additional “if” statement.
