### ISSUE TITLE
Rendering of Appendix and of callouts in PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iec#60]
From https://github.com/metanorma/metanorma-iec/issues/56:

````
[%appendix]
=== Appendix 1

[[samplecode]]
.Sample Code
====

[source,ruby]
--
puts "Hello, world."
%w{a b c}.each do |x| <1>
  puts x
end
--
<1> This is an annotation
====
````

The correct behaviour is

* to insert an "Appendix n" caption before the title of an `<appendix>`
* to insert a blank line between `<sourcecode>` and the listing of callouts following it.

**Comment by Intelligent2013** [comment]
Fixed.

Resulted PDF: https://github.com/metanorma/mn-native-pdf/raw/gh-pages/documents/iec-rice.pdf

![изображение](https://user-images.githubusercontent.com/5559926/83561087-ed2dea80-a51f-11ea-9d19-97f4725e7f05.png)
