### ISSUE TITLE
Discrepancies between PDF and DOC outputs

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iec#62]
I have opened this ticket in order to discuss about the discrepancies between PDF vs DOC, with the purpose to achieve a more similar layout (if possible). 
In regard to PDF, @Intelligent2013 is taking guidance from these documents layout: https://github.com/metanorma/mn-native-pdf/issues/109.

The discrepancies are:

1. Page numbering. In DOC, Roman numbers are used (in preface pages), while in PDF, Arabic numbers are used.

DOC:
![diff1-doc](https://user-images.githubusercontent.com/33627611/83218733-8930ae00-a13c-11ea-8cce-ec2cb751163b.PNG)

PDF:
![diff1-pdf](https://user-images.githubusercontent.com/33627611/83218731-86ce5400-a13c-11ea-8e8d-acaf75eaf1dd.PNG)

2.  Warning block formatting differs. (Also applies for caption blocks.)

DOC:
![diff2-doc](https://user-images.githubusercontent.com/33627611/83218979-27247880-a13d-11ea-8f9d-03da83c43925.PNG)

PDF:
![diff2-pdf](https://user-images.githubusercontent.com/33627611/83218982-2ab7ff80-a13d-11ea-8461-a881550e84f7.PNG)

3. Main titles differ. "INTERNATIONAL ELECTROTECHNICAL COMMISSION" is missing in PDF.

DOC:
![diff3-doc](https://user-images.githubusercontent.com/33627611/83219245-f09b2d80-a13d-11ea-92fc-080a9973cec1.PNG)

PDF:
![diff3-pdf](https://user-images.githubusercontent.com/33627611/83219256-f3961e00-a13d-11ea-901e-e2369509476a.PNG)

4. Inline equations slightly differ. In DOC, the equation gets indented.

DOC:
![diff4-doc](https://user-images.githubusercontent.com/33627611/83219611-c8f89500-a13e-11ea-99a8-1a56fcfb1447.PNG)

PDF:
![diff4-pdf](https://user-images.githubusercontent.com/33627611/83219617-cac25880-a13e-11ea-8e27-bec9a1c9d293.PNG)

*Markup:*
````
=== gelatinization time
stem:[t_90]

time necessary for 90 % of the kernels to pass from their natural state to the _gel state_ (<<gel_state>>)

[.source]
<<ISO14864,clause 3.1>>
````

5. Blank subclause headings are rendered differently. 

DOC:
![diff5-doc](https://user-images.githubusercontent.com/33627611/83219933-a74bdd80-a13f-11ea-89b1-0da9800c5472.PNG)

PDF:
![diff5-pdf](https://user-images.githubusercontent.com/33627611/83219939-a9ae3780-a13f-11ea-85aa-c74c0e7419c8.PNG)

*Markup:*
````
==== {blank}

The mass fraction of moisture, determined in accordance with <<ISO712>>, using an oven complying with the requirements of <<IEC61010-2>>, shall not be greater than 15 %.footnote:[Formerly denoted as 15 % (m/m).]
````

6. Block equations get aligned differently. In DOC, they are left-aligned, while in PDF, they are center-aligned.

DOC:
![diff6-doc](https://user-images.githubusercontent.com/33627611/83220354-bd0dd280-a140-11ea-9fb0-d086cf084822.PNG)

PDF:
![diff6-pdf](https://user-images.githubusercontent.com/33627611/83220358-c008c300-a140-11ea-8143-a32ccf3a5c3e.PNG)

*Markup:*
````
[stem]
++++
r = 1 %
++++

where

stem:[r]:: is the repeatability limit.
````

7. Bibliography section differs. In DOC, the references are numbered -- in PDF they're not. And the title has different formatting.

DOC:
![diff7-doc](https://user-images.githubusercontent.com/33627611/83220613-83899700-a141-11ea-9be4-97e9858b1f45.PNG)

PDF:
![diff7-pdf](https://user-images.githubusercontent.com/33627611/83220619-86848780-a141-11ea-8b1e-b4df6638e9c2.PNG)

**Comment by opoudjis** [comment]
Would have been helpful to identify which of the two is wrong.

1. DOC is wrong about page numbers.
2. DOC is wrong about cover page warnings. (@manuel489 what do you mean by caption blocks? Need examples.)
3. PDF is wrong about internal title
4. DOC is wrong about indenting formulas in terms
5. Don't know, needs escalation: @ronaldtse 
6. DOC is wrong about formula position
7. DOC is wrong about bibliography

What's happened is simple: I had assumed that IEC was following ISO styling. It doesn't.

**Comment by opoudjis** [comment]
Splitting this ticket.

**Comment by opoudjis** [comment]
5, default inline headers, is ISO editorial practice. I'll override it.
