### ISSUE TITLE
Discrepancies between PDF and DOC outputs: PDF fixes

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iec#64]
_From: https://github.com/metanorma/metanorma-iec/issues/62_

3. Main titles differ. "INTERNATIONAL ELECTROTECHNICAL COMMISSION" is missing in PDF.

DOC:
![diff3-doc](https://user-images.githubusercontent.com/33627611/83219245-f09b2d80-a13d-11ea-92fc-080a9973cec1.PNG)

PDF:
![diff3-pdf](https://user-images.githubusercontent.com/33627611/83219256-f3961e00-a13d-11ea-901e-e2369509476a.PNG)

**Comment by Intelligent2013** [comment]
@opoudjis Looks like manuel489 compared Foreword page from DOC with Frontpage from PDF.

Here is foreword page from resulted PDF (iec-rice) with `INTERNATIONAL ELECTROTECHNICAL COMMISSION` at top:
![изображение](https://user-images.githubusercontent.com/5559926/83781570-669c1900-a697-11ea-949b-af67a02b7d9d.png)

Here is front page (page after introduction) from resulted PDF (iec-rice) without `INTERNATIONAL ELECTROTECHNICAL COMMISSION`:
![изображение](https://user-images.githubusercontent.com/5559926/83781758-a105b600-a697-11ea-8520-e31145d6084a.png)

Initially I put `INTERNATIONAL ELECTROTECHNICAL COMMISSION` on both pages (I found commented code in xslt). But regarding https://github.com/metanorma/mn-native-pdf/issues/112 I've removed `INTERNATIONAL ELECTROTECHNICAL COMMISSION` from frontpage. 
Regarding https://github.com/metanorma/mn-native-pdf/issues/111 I put `INTERNATIONAL ELECTROTECHNICAL COMMISSION` only on Foreword page.

@opoudjis @ronaldtse Please confirm that I should to return `INTERNATIONAL ELECTROTECHNICAL COMMISSION` to frontpage again.

**Comment by ronaldtse** [comment]
@Intelligent2013 @opoudjis @manuel489 
* Foreword page has "INTERNATIONAL ...".
* Content page header never had it.

Are we doing the right thing here?

**Comment by manuel489** [comment]
> @opoudjis Looks like manuel489 compared Foreword page from DOC with Frontpage from PDF.

Well, I don't think so. I was actually comparing front pages in both versions.

DOC:
![diff-doc](https://user-images.githubusercontent.com/33627611/83791161-58ce9f80-a667-11ea-94f9-ee7240fac709.PNG)

PDF:
![diff-pdf](https://user-images.githubusercontent.com/33627611/83791169-5b30f980-a667-11ea-9e98-88bd7cd72ecb.PNG)

**Comment by Intelligent2013** [comment]
> Well, I don't think so. I was actually comparing front pages in both versions.

@manuel489 sorry, I've looked at page number ( -1- vs -7-) and thought that these a different sections...

**Comment by Intelligent2013** [comment]
>     * Foreword page has "INTERNATIONAL ...".
> 
>     * Content page header never had it.
> 
> 
> Are we doing the right thing here?

In PDF it so.

**Comment by manuel489** [comment]
> @manuel489 sorry, I've looked at page number ( -1- vs -7-) and thought that these a different sections...

@Intelligent2013 , no worries. Good catch btw! 👍

**Comment by ronaldtse** [comment]
@manuel489 does this mean that the DOC output should be fixed? (i.e. Only foreword page should have "INTERNATIONAL ...", the page with Scope should not)

**Comment by manuel489** [comment]
> i.e. Only foreword page should have "INTERNATIONAL ...", the page with Scope should not

@ronaldtse , based on this statement, yes.

**Comment by manuel489** [comment]
> @manuel489 does this mean that the DOC output should be fixed? (i.e. Only foreword page should have "INTERNATIONAL ...", the page with Scope should not)

> > i.e. Only foreword page should have "INTERNATIONAL ...", the page with Scope should not
> 
> @ronaldtse , based on this statement, yes.

New ticket created in https://github.com/metanorma/metanorma-iec/issues/65. Closing.
