### ISSUE TITLE
IEC terms and definitions boilerplate is slightly different!

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#7]
I was pointed to this by the IEC terminology coordinator:

https://www.iec.ch/standardsdev/resources/draftingpublications/directives/subdivision/terms_definitions.htm

![image](https://user-images.githubusercontent.com/11865/65064498-2e429680-d9b3-11e9-91db-335386f6bd8d.png)

See the difference? "IEC Electropedia" goes FIRST in IEC documents.

**Comment by ronaldtse** [comment]
IEC templates also indicate that IEC goes first.

<img width="468" alt="Screen Shot 2019-09-18 at 2 06 04 AM" src="https://user-images.githubusercontent.com/11865/65067346-df97fb00-d9b8-11e9-96c5-9656bc244675.png">

**Comment by opoudjis** [comment]
Oh FFS.

**Comment by ronaldtse** [comment]
Namaste.
