### ISSUE TITLE
Template for circulation cover page

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iec#95]
https://github.com/metanorma/metanorma-iec/issues/48 is introducing various elements to populate a pre-publication checklist page, which is generated only in PDF. It's not enough for me to supply the XML values for @Intelligent2013 to use; we also need to provide guidance to users as to how to populate those values for IEC. 

I request a separate template be generated, to document the required fields.

**Comment by manuel489** [comment]
Changes are ready to review in https://github.com/metanorma/mn-templates-iec/pull/18

**Comment by opoudjis** [comment]
Answering your queries:

> 1. Which attribute would set the stage of the standard (e.g. FDIS, CDV, RVC, etc.) ?

In principle, all abbreviations are recognised in stage, although we prefer using the numbers. In practice, I've missed the simple abbreviations, and I'll put them back in. So `:stage: 50` is recognised, and so is `:stage: RFDIS`; I'm putting in the simple codes, so that `:stage: FDIS` is recognised.

> 2. In the sample you shared, the :stage: attribute has a number as a value. But according to the documentation, it should be an abbreviation.

Both are allowed. I prefer the numbers, because there's less room for doubt, and the numbers are what is passed on to the XML.

> 3. Has the "Supersedes Documents" field any attribute associated?

It is associated with `:obsoletes:`, but I have not licensed that attribute for IEC, and @Intelligent2013 has forgotten to request it explicitly of me. Will action.

**Comment by manuel489** [comment]
> Answering your queries...

Thanks @opoudjis!  I have applied the changes.

**Comment by manuel489** [comment]
Changes are approved and merged.
Closing.
