### ISSUE TITLE
Superseded Documents

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iec#99]
Follow-on from https://github.com/metanorma/metanorma-iec/issues/95:

The *Supersedes Documents* field in the document template needs to be populated. It is populated from `//bibdata/relation[@type = 'obsoletes']/bibitem/docidentifier`, and there can be multiple instances of it:

````
<bibdata>
....
<relation type="obsoletes">
<bibitem>
<title>--</title>
<docidentifier>104/820/CDV</docidentifier>
</bibitem>
</relation>
<relation type="obsoletes">
<bibitem>
<title>--</title>
<docidentifier>104/852A/RVC</docidentifier>
</bibitem>
</relation>
....
</bibdata>
````

**Comment by Intelligent2013** [comment]
Done.
![изображение](https://user-images.githubusercontent.com/5559926/105579524-4c36bd00-5d98-11eb-832b-0b3e543d5031.png)

Previous source field was:
```
bibdata/relation[@type='supersedes']/bibitem/docnumber
```
(https://github.com/metanorma/mn-native-pdf/commit/866ae450f84846a131964eee12d23bdf20825998#diff-b1e83f67c3a4774c1acb199034855fa42a11cf33ce1aec0a8ee1a44febbb28a3)
Really I don't remember the reason of this previous solution...
